kind: pipeline
name: default

steps:
- name: build
  image: openjdk:8-jdk
  commands:
  - chmod +x ./gradlew
  - ./gradlew clean build

- name: docker
  image: plugins/docker
  settings:
    repo: prakharjain/DevOps
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password